version: "3.3"
services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8080:8080" 
    links: 
      - redis
    environment: 
      REDIS_LOCAL_URL: "redis:6379" 
    networks:
      - minesweeper
  redis:
    image: "redis:alpine" 
    networks:
      - minesweeper
    ports:
      - "6379:6379" 
networks:
  minesweeper: 